### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rabbadab**
Removed some settings resources that trows an error when you try to add them right now. 
Also just changed so the text does not mention volkswagenconnect configuration block.

### CODE REVIEW

**Review by lendy007 — CHANGES_REQUESTED** [review]
Hello,

I am using all three attributes you wanted to remove without any issues... Just - `kodiaq_combustion_engine_heating_ventilation_status` should be - `combustion_engine_heatingventilation_status `only... I will fix this in description. Btw. when you do not specify any of these items, plugin will automatically create all entities which are available for your car.

**Comment by rabbadab** [comment]
Ahh strange maybe there was the kodiaq_combustion_engine_heating_ventilation_status that made the others below to fail. 
Then I will just remove everything in resource list and let the magic happen.
Ohh would be cool if all the entities would be linked to a device and you gather all of them under that. The car VIN should do as a unique ID...
https://developers.home-assistant.io/docs/device_registry_index

**Comment by lendy007** [comment]
I am not so skilled in Home Assistant development, I am happy I was able to get it working in current state :) But feel free to perform changes which will do the trick, I will be happy to merge it into the code.

**Comment by Farfar** [comment]
> Ahh strange maybe there was the kodiaq_combustion_engine_heating_ventilation_status that made the others below to fail.
> Then I will just remove everything in resource list and let the magic happen.
> Ohh would be cool if all the entities would be linked to a device and you gather all of them under that. The car VIN should do as a unique ID...
> https://developers.home-assistant.io/docs/device_registry_index

I will take a look and see if I can make it happen.
Haven't had much time for coding the last week but starting to get service call working, will take a look and see if we can make this work.

**Pull request closed without merging**
